version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_URL: mongodb://saber:saber@mongo:27017
    env_file:
      - .env.local-docker
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: saber
      MONGO_INITDB_ROOT_PASSWORD: saber
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
